### ISSUE TITLE
android Q beta4下无法正常使用

### ISSUE THREAD

**Issue by landenzhang** [ccg2018/ClashA#10]
android Q beta4下无法正常使用，能运行，能导入配置，点开启后就无反应，直到卡死。

**Comment by landenzhang** [comment]
目前更新到Beta3后，能运行，能导入配置，点开始后，直接报错，无法开启vpn。

**Comment by cubarco** [comment]
@ccg2018,
golang的问题，需要用新版本go编译
https://github.com/golang/go/issues/29674

**Comment by neatgz** [comment]
https://github.com/ccg2018/ClashA/issues/18#issuecomment-541497614
