### ISSUE TITLE
请问下右上角的not vpn 是什么功能？

### ISSUE THREAD

**Issue by pastpassenger** [ccg2018/ClashA#12]

**Comment by LM-Firefly** [comment]
和SS-Android 的 仅代理 一样 不建立VPN 需要代理的软件 通过设置本地http或者sock5代理上网 beta3 已经移动到 Global Settings 里面了

**Comment by pastpassenger** [comment]
> 和SS-Android 的 仅代理 一样 不建立VPN 需要代理的软件 通过设置本地http或者sock5代理上网 beta3 已经移动到 Global Settings 里面了

非常感谢
