### ISSUE TITLE
android 10 适配

### ISSUE THREAD

**Issue by msdogo** [ccg2018/ClashA#18]
大佬，升级到 Android 10小猫咪按钮电了没啥反应... vpn连不上

**Comment by jxiaox** [comment]
+1

**Comment by ibule** [comment]
+1

**Comment by kid-oh** [comment]
+1

**Comment by ChiachiCheng** [comment]
pixel 2xl，安卓10 10月安全补丁，同样问题。

**Comment by neatgz** [comment]
适配 Android 10 的版本，作者发布在 telegram 群里了。
https://t.me/clash_android_discuss

> ClashA-universal-release-0.0.1-beta4.apk
support Android 10
use Dreamacro/clash-dashboard
support ipv6
update Clash lib
dashboard to local
