### ISSUE TITLE
0.0.1-beta3 通用安装包装手机，到提醒vpn界面无法点击确定。

### ISSUE THREAD

**Issue by qq66711607** [ccg2018/ClashA#21]
手机型号：华为mate20pro ud 8+256 国行，emui 9.1.0.135 Android 9

**Comment by LM-Firefly** [comment]
检查一下是不是有应用显示在屏幕上层  护眼模式 防蓝光 或者悬浮球一类的软件

**Comment by qq66711607** [comment]
应该说点击确定没有反应
