### ISSUE TITLE
android 10上貌似无法运行?

### ISSUE THREAD

**Issue by pangmf** [ccg2018/ClashA#23]
在android 10上运行时点连接后没有反应

**Comment by xuhaoyang** [comment]
@pangmf 0.0.1-beta4 support Android 10

**Comment by ccg2018** [comment]
0.0.1-beta4 support Android 10

**Comment by ccg2018** [comment]
https://github.com/ccg2018/ClashA/releases/tag/0.0.1-beta4-night-201911030325
