### ISSUE TITLE
关于IPV6

### ISSUE THREAD

**Issue by Olivercoco** [ccg2018/ClashA#25]
Facebook 和Instagram  app 访问异常，查日志 发现多个疑似FB的IPV6请求，但本地和节点均不支持IPV6，初步认为 这是访问异常的原因。使用神机规则，Android 9，ClashA beta3。请问有什么解决方案吗？或者请问有何建议？
![photo_2019-10-27_14-39-55](https://user-images.githubusercontent.com/39828052/67630758-a90ea380-f8c7-11e9-91ca-3b8d3ecfd5c0.jpg)

**Comment by Olivercoco** [comment]
通过规则分流解决。

**Comment by ccg2018** [comment]
@Olivercoco 之后提供关闭ipv6 支持的选项，现阶段建议配置好nameserver和fallback 开启redir-host 能解决这个问题

**Comment by Olivercoco** [comment]
已添加IPV6开关 ，问题解决。
