### ISSUE TITLE
False positive from Malwarebytes

### ISSUE THREAD

**Issue by allanb1979** [ccg2018/ClashA#26]
![Screenshot_2019-11-06-19-17-22-404_org malwarebytes antimalware](https://user-images.githubusercontent.com/23328553/68294911-31612580-00cc-11ea-8d5c-101e4afbadaa.jpg)

**Comment by ccg2018** [comment]
What is antivirus software?

I think it is a misjudgment of antivirus software.

**Comment by ccg2018** [comment]
https://virusscan.jotti.org/en-US/filescanjob/mih9rhbpq2

http://www.virscan.org/scan/299f3af7d38f4d51cf17e5665812a444

**Comment by allanb1979** [comment]
Yes, i checked with several others as well. Better report it to Malwarebytes as a false positive. 

Your app is working perfectly btw, thank you for the effort :-)
