### ISSUE TITLE
静态IP vmss节点 无法测速和连接

### ISSUE THREAD

**Issue by w422417869** [ccg2018/ClashA#33]
手机WIFI连接 设置成静态IP后， 无法使用测速和连接

换成手机4G网络 或者用其他SS节点就可以测速和连接。

**Comment by xuhaoyang** [comment]
@w422417869 无法使用，会有log，提供log，才能解决问题

**Comment by w422417869** [comment]
@xuhaoyang 不好意思，现在又可以了。我再观察一段时间，如果再出现，回来贴上log

**Comment by w422417869** [comment]
开关飞行模式 可解决这个问题。。可能是DNS污染的原因
