### ISSUE TITLE
DNS错误

### ISSUE THREAD

**Issue by 3andero** [ccg2018/ClashA#4]
配置文件和CFW (clash for windows)上的类似（删除了CFW bypass部分，电脑上的配置没有DNS），网络条件相同（手机开热点，同样的服务器），访问同样的网站，电脑上可以访问，手机端的chrome显示 “DNS_PROBE_FINISHED_NXDOMAIN”错误。
手机端的DNS配置部分如下：
```dns:
  enable: true # set true to enable dns (default is false)
  ipv6: false # default is false
  listen: 0.0.0.0:53
  # enhanced-mode: redir-host
  nameserver:
    - 114.114.114.114
    - tls://dns.rubyfish.cn:853 # dns over tls
  fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
    - 1.1.1.1
    - 8.8.8.8 
```

有没有DNS配置都测试过，问题没有变化。

测试使用的网站是：
www.jamestown.org
www.rfa.org
www.rsf.org
这些网站的共同特点是他们没有规则中被明确指定"Proxy"，理论上它们应该被归类为"Others" -> "Proxy"，但是或许是DNS解析上的问题，他们没有被归类为Others。

另一个有趣的现象是，把chrome（手机端）放在那里不管，过大概一分钟，这些网站有时候就能够加载出来了。

**Comment by ccg2018** [comment]
配置里面配置DNS不生效，在全局设置配置DNS设置
