### ISSUE TITLE
安卓4.4.2的电视盒子上安装失败

### ISSUE THREAD

**Issue by leegang** [ccg2018/ClashA#6]
安卓4.4.2的电视盒子上安装失败

adb shell
pm install ClashA-arm64-v8a-release-0.0.1-pre8.apk
pkg: ClashA-arm64-v8a-release-0.0.1-pre8.apk
Failure [INSTALL_FAILED_OLDER_SDK]

**Comment by qq66711607** [comment]
rk312x android4.4.4同样安装不了

**Comment by ccg2018** [comment]
不支持Android5.0之前设备
