### ISSUE TITLE
能否添加一个分应用代理或者排除代理应用吗？

### ISSUE THREAD

**Issue by BaileyZyp** [ccg2018/ClashA#7]
我开着ClashA的时候玩刺激战场不能进入游戏
我配置了分流 腾讯旗下的域名设置的直连

**Comment by Travisss** [comment]
我也是很多直链的网站都卡不开。不知道规则这块是怎么回事

**Comment by trysh** [comment]
强烈希望有“分应用”功能

**Comment by ccg2018** [comment]
@trysh 会有，但无计划安排

**Comment by trysh** [comment]
> @trysh 会有，但无计划安排

十分感谢。辛苦了。有收费功能或捐赠计划吗？愿意支持。
